services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - pet_name_game_network

  db:
    image: postgres:14.10-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - pet_name_game_network

networks:
  pet_name_game_network:
    driver: bridge

volumes:
  postgres_data:
