"""remove realtionships

Revision ID: 2f502d434878
Revises: e7b7bb63e12f
Create Date: 2024-02-27 01:48:46.411098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2f502d434878'
down_revision: Union[str, None] = 'e7b7bb63e12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cardboardlink')
    op.add_column('game_boards', sa.Column('animals', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_boards', 'animals')
    op.create_table('cardboardlink',
    sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['game_boards.id'], name='cardboardlink_board_id_fkey'),
    sa.ForeignKeyConstraint(['card_id'], ['animal_cards.id'], name='cardboardlink_card_id_fkey'),
    sa.PrimaryKeyConstraint('card_id', 'board_id', name='cardboardlink_pkey')
    )
    # ### end Alembic commands ###
