"""add link table for card and board relationship and some columns on the gameboard

Revision ID: cbd7177e994d
Revises: f9d2dd138620
Create Date: 2024-02-27 00:50:09.242903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cbd7177e994d'
down_revision: Union[str, None] = 'f9d2dd138620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardboardlink',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['game_boards.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['animal_cards.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'board_id')
    )
    op.add_column('game_boards', sa.Column('game_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('game_boards', sa.Column('animal_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('game_boards', sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_boards', 'gender')
    op.drop_column('game_boards', 'animal_type')
    op.drop_column('game_boards', 'game_type')
    op.drop_table('cardboardlink')
    # ### end Alembic commands ###
